name: PullRequest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  buildMac:
    name: Build macOS
    runs-on: ${{ matrix.macos }}
    strategy:
      matrix:
        macos: [ macos-13 ]
        xcode: [ Xcode_15.2 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Investigate available XCode versions
        run: ls -n /Applications/ | grep Xcode*
      - name: Set XCode Version
        run: |
          sudo xcode-select -s /Applications/${{ matrix.xcode }}.app
          xcodebuild -version
          xcode-select --print-path
      - name: Install build environment
        run: scripts/darwin/install.sh
      - name: Show cmake version
        run: cmake --version
      - name: Build project
        run: scripts/darwin/build.sh
      - name: Archive artifact
        uses: actions/upload-artifact@v4
        if: ${{ success() }}
        with:
          name: DLTViewer-${{ matrix.macos }}-x86_64
          path: build/dist/DLTViewer*.tgz
